/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGuilangScopeProvider extends DelegatingScopeProvider {
}
