/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.guilang.impl;

import dk.sdu.mdsd.guilang.guilang.ButtonSpecOptions;
import dk.sdu.mdsd.guilang.guilang.GuilangPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Button Spec Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ButtonSpecOptionsImpl extends MinimalEObjectImpl.Container implements ButtonSpecOptions
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ButtonSpecOptionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GuilangPackage.Literals.BUTTON_SPEC_OPTIONS;
  }

} //ButtonSpecOptionsImpl
