/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang;

import dk.sdu.mdsd.guilang.AbstractGuilangRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GuilangRuntimeModule extends AbstractGuilangRuntimeModule {
}
