/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang;

import dk.sdu.mdsd.guilang.GuilangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GuilangStandaloneSetup extends GuilangStandaloneSetupGenerated {
  public static void doSetup() {
    new GuilangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
