/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.ui.contentassist;

import dk.sdu.mdsd.guilang.ui.contentassist.AbstractGuilangProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GuilangProposalProvider extends AbstractGuilangProposalProvider {
}
