/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.ui;

import dk.sdu.mdsd.guilang.ui.AbstractGuilangUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GuilangUiModule extends AbstractGuilangUiModule {
  public GuilangUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
