/*
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.mdsd.guilang.parser.antlr.internal.InternalGuilangParser;
import dk.sdu.mdsd.guilang.services.GuilangGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GuilangParser extends AbstractAntlrParser {

	@Inject
	private GuilangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGuilangParser createParser(XtextTokenStream stream) {
		return new InternalGuilangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "GUI";
	}

	public GuilangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GuilangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
