/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.guilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.guilang.guilang.And#getLeft <em>Left</em>}</li>
 *   <li>{@link dk.sdu.mdsd.guilang.guilang.And#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getAnd()
 * @model
 * @generated
 */
public interface And extends Require
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Require)
   * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getAnd_Left()
   * @model containment="true"
   * @generated
   */
  Require getLeft();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.guilang.guilang.And#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Require value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Require)
   * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getAnd_Right()
   * @model containment="true"
   * @generated
   */
  Require getRight();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.guilang.guilang.And#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Require value);

} // And
