/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.guilang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Button Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.guilang.guilang.ButtonSpec#getRef <em>Ref</em>}</li>
 *   <li>{@link dk.sdu.mdsd.guilang.guilang.ButtonSpec#getOptions <em>Options</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getButtonSpec()
 * @model
 * @generated
 */
public interface ButtonSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ref</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' reference.
   * @see #setRef(Button)
   * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getButtonSpec_Ref()
   * @model
   * @generated
   */
  Button getRef();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.guilang.guilang.ButtonSpec#getRef <em>Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Button value);

  /**
   * Returns the value of the '<em><b>Options</b></em>' containment reference list.
   * The list contents are of type {@link dk.sdu.mdsd.guilang.guilang.ButtonSpecOptions}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Options</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Options</em>' containment reference list.
   * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getButtonSpec_Options()
   * @model containment="true"
   * @generated
   */
  EList<ButtonSpecOptions> getOptions();

} // ButtonSpec
