/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.guilang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends Entity
{
} // Element
