/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.guilang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dk.sdu.mdsd.guilang.guilang.GuilangFactory
 * @model kind="package"
 * @generated
 */
public interface GuilangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "guilang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sdu.dk/mdsd/guilang/Guilang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "guilang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GuilangPackage eINSTANCE = dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl.init();

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.GUIImpl <em>GUI</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.GUIImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getGUI()
   * @generated
   */
  int GUI = 0;

  /**
   * The feature id for the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI__MAIN = 0;

  /**
   * The number of structural features of the '<em>GUI</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GUI_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.UnitImpl <em>Unit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.UnitImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getUnit()
   * @generated
   */
  int UNIT = 1;

  /**
   * The feature id for the '<em><b>Layout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIT__LAYOUT = 0;

  /**
   * The feature id for the '<em><b>Specifications</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIT__SPECIFICATIONS = 1;

  /**
   * The number of structural features of the '<em>Unit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNIT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.EntityImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.LayoutTypeImpl <em>Layout Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.LayoutTypeImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getLayoutType()
   * @generated
   */
  int LAYOUT_TYPE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_TYPE__NAME = ENTITY__NAME;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_TYPE__ENTITIES = ENTITY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Layout Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_TYPE_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.LayoutImpl <em>Layout</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.LayoutImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getLayout()
   * @generated
   */
  int LAYOUT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT__NAME = LAYOUT_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT__ENTITIES = LAYOUT_TYPE__ENTITIES;

  /**
   * The number of structural features of the '<em>Layout</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_FEATURE_COUNT = LAYOUT_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.VerticalImpl <em>Vertical</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.VerticalImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getVertical()
   * @generated
   */
  int VERTICAL = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL__NAME = LAYOUT_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL__ENTITIES = LAYOUT_TYPE__ENTITIES;

  /**
   * The number of structural features of the '<em>Vertical</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL_FEATURE_COUNT = LAYOUT_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.HorizontalImpl <em>Horizontal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.HorizontalImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getHorizontal()
   * @generated
   */
  int HORIZONTAL = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL__NAME = LAYOUT_TYPE__NAME;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL__ENTITIES = LAYOUT_TYPE__ENTITIES;

  /**
   * The number of structural features of the '<em>Horizontal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL_FEATURE_COUNT = LAYOUT_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.ElementImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = ENTITY__NAME;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = ENTITY_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.LabelImpl <em>Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.LabelImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getLabel()
   * @generated
   */
  int LABEL = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL__NAME = ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ButtonImpl <em>Button</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.ButtonImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getButton()
   * @generated
   */
  int BUTTON = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON__NAME = ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Button</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.InputImpl <em>Input</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.InputImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getInput()
   * @generated
   */
  int INPUT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT__NAME = ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Input</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.CheckboxImpl <em>Checkbox</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.CheckboxImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getCheckbox()
   * @generated
   */
  int CHECKBOX = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX__NAME = ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Checkbox</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.SpecificationsImpl <em>Specifications</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.SpecificationsImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getSpecifications()
   * @generated
   */
  int SPECIFICATIONS = 12;

  /**
   * The feature id for the '<em><b>Specifications</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFICATIONS__SPECIFICATIONS = 0;

  /**
   * The number of structural features of the '<em>Specifications</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFICATIONS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.SpecificationImpl <em>Specification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.SpecificationImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getSpecification()
   * @generated
   */
  int SPECIFICATION = 13;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFICATION__TYPE = 0;

  /**
   * The number of structural features of the '<em>Specification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SPECIFICATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.LayoutSpecImpl <em>Layout Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.LayoutSpecImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getLayoutSpec()
   * @generated
   */
  int LAYOUT_SPEC = 14;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_SPEC__REF = 0;

  /**
   * The number of structural features of the '<em>Layout Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYOUT_SPEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.VerticalSpecImpl <em>Vertical Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.VerticalSpecImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getVerticalSpec()
   * @generated
   */
  int VERTICAL_SPEC = 15;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL_SPEC__REF = 0;

  /**
   * The number of structural features of the '<em>Vertical Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VERTICAL_SPEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.HorizontalSpecImpl <em>Horizontal Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.HorizontalSpecImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getHorizontalSpec()
   * @generated
   */
  int HORIZONTAL_SPEC = 16;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL_SPEC__REF = 0;

  /**
   * The number of structural features of the '<em>Horizontal Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HORIZONTAL_SPEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.LabelSpecImpl <em>Label Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.LabelSpecImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getLabelSpec()
   * @generated
   */
  int LABEL_SPEC = 17;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_SPEC__REF = 0;

  /**
   * The number of structural features of the '<em>Label Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_SPEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ButtonSpecImpl <em>Button Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.ButtonSpecImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getButtonSpec()
   * @generated
   */
  int BUTTON_SPEC = 18;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_SPEC__REF = 0;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_SPEC__OPTIONS = 1;

  /**
   * The number of structural features of the '<em>Button Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_SPEC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ButtonSpecOptionsImpl <em>Button Spec Options</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.ButtonSpecOptionsImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getButtonSpecOptions()
   * @generated
   */
  int BUTTON_SPEC_OPTIONS = 19;

  /**
   * The number of structural features of the '<em>Button Spec Options</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUTTON_SPEC_OPTIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.InputSpecImpl <em>Input Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.InputSpecImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getInputSpec()
   * @generated
   */
  int INPUT_SPEC = 20;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_SPEC__REF = 0;

  /**
   * The feature id for the '<em><b>Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_SPEC__OPTIONS = 1;

  /**
   * The number of structural features of the '<em>Input Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_SPEC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.InputSpecOptionsImpl <em>Input Spec Options</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.InputSpecOptionsImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getInputSpecOptions()
   * @generated
   */
  int INPUT_SPEC_OPTIONS = 21;

  /**
   * The number of structural features of the '<em>Input Spec Options</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_SPEC_OPTIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.CheckboxSpecImpl <em>Checkbox Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.CheckboxSpecImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getCheckboxSpec()
   * @generated
   */
  int CHECKBOX_SPEC = 22;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_SPEC__REF = 0;

  /**
   * The number of structural features of the '<em>Checkbox Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_SPEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.SizeSpecImpl <em>Size Spec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.SizeSpecImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getSizeSpec()
   * @generated
   */
  int SIZE_SPEC = 23;

  /**
   * The feature id for the '<em><b>Width</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_SPEC__WIDTH = 0;

  /**
   * The feature id for the '<em><b>Height</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_SPEC__HEIGHT = 1;

  /**
   * The number of structural features of the '<em>Size Spec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIZE_SPEC_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ValidateImpl <em>Validate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.ValidateImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getValidate()
   * @generated
   */
  int VALIDATE = 24;

  /**
   * The feature id for the '<em><b>Validations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATE__VALIDATIONS = 0;

  /**
   * The number of structural features of the '<em>Validate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALIDATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.TextValidateImpl <em>Text Validate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.TextValidateImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getTextValidate()
   * @generated
   */
  int TEXT_VALIDATE = 25;

  /**
   * The feature id for the '<em><b>Validation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_VALIDATE__VALIDATION = INPUT_SPEC_OPTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Text Validate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_VALIDATE_FEATURE_COUNT = INPUT_SPEC_OPTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.RegexValidateImpl <em>Regex Validate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.RegexValidateImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getRegexValidate()
   * @generated
   */
  int REGEX_VALIDATE = 26;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGEX_VALIDATE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Regex Validate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGEX_VALIDATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.RegexVariableValidateImpl <em>Regex Variable Validate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.RegexVariableValidateImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getRegexVariableValidate()
   * @generated
   */
  int REGEX_VARIABLE_VALIDATE = 27;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGEX_VARIABLE_VALIDATE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Regex Variable Validate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGEX_VARIABLE_VALIDATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.RegexVariableRefImpl <em>Regex Variable Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.RegexVariableRefImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getRegexVariableRef()
   * @generated
   */
  int REGEX_VARIABLE_REF = 28;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGEX_VARIABLE_REF__REF = 0;

  /**
   * The number of structural features of the '<em>Regex Variable Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REGEX_VARIABLE_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.PresetTextValidateImpl <em>Preset Text Validate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.PresetTextValidateImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getPresetTextValidate()
   * @generated
   */
  int PRESET_TEXT_VALIDATE = 29;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRESET_TEXT_VALIDATE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Preset Text Validate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRESET_TEXT_VALIDATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.CheckboxValidateImpl <em>Checkbox Validate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.CheckboxValidateImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getCheckboxValidate()
   * @generated
   */
  int CHECKBOX_VALIDATE = 30;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_VALIDATE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Checkbox Validate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECKBOX_VALIDATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.RequireElementsImpl <em>Require Elements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.RequireElementsImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getRequireElements()
   * @generated
   */
  int REQUIRE_ELEMENTS = 31;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRE_ELEMENTS__ELEMENTS = BUTTON_SPEC_OPTIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Require Elements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRE_ELEMENTS_FEATURE_COUNT = BUTTON_SPEC_OPTIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.RequireImpl <em>Require</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.RequireImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getRequire()
   * @generated
   */
  int REQUIRE = 32;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRE__EXP = 0;

  /**
   * The number of structural features of the '<em>Require</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REQUIRE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.OrImpl <em>Or</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.OrImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getOr()
   * @generated
   */
  int OR = 33;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__EXP = REQUIRE__EXP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__LEFT = REQUIRE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR__RIGHT = REQUIRE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_FEATURE_COUNT = REQUIRE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.AndImpl <em>And</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.AndImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getAnd()
   * @generated
   */
  int AND = 34;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__EXP = REQUIRE__EXP;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__LEFT = REQUIRE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND__RIGHT = REQUIRE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_FEATURE_COUNT = REQUIRE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.NotImpl <em>Not</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.NotImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getNot()
   * @generated
   */
  int NOT = 35;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT__EXP = REQUIRE__EXP;

  /**
   * The number of structural features of the '<em>Not</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_FEATURE_COUNT = REQUIRE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ElementRefImpl <em>Element Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mdsd.guilang.guilang.impl.ElementRefImpl
   * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getElementRef()
   * @generated
   */
  int ELEMENT_REF = 36;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_REF__EXP = REQUIRE__EXP;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_REF__REF = REQUIRE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Element Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_REF_FEATURE_COUNT = REQUIRE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.GUI <em>GUI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GUI</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.GUI
   * @generated
   */
  EClass getGUI();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.GUI#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Main</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.GUI#getMain()
   * @see #getGUI()
   * @generated
   */
  EReference getGUI_Main();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Unit <em>Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unit</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Unit
   * @generated
   */
  EClass getUnit();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.Unit#getLayout <em>Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Layout</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Unit#getLayout()
   * @see #getUnit()
   * @generated
   */
  EReference getUnit_Layout();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.Unit#getSpecifications <em>Specifications</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Specifications</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Unit#getSpecifications()
   * @see #getUnit()
   * @generated
   */
  EReference getUnit_Specifications();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.guilang.guilang.Entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Entity#getName()
   * @see #getEntity()
   * @generated
   */
  EAttribute getEntity_Name();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Layout <em>Layout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Layout
   * @generated
   */
  EClass getLayout();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.LayoutType <em>Layout Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout Type</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.LayoutType
   * @generated
   */
  EClass getLayoutType();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.guilang.guilang.LayoutType#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.LayoutType#getEntities()
   * @see #getLayoutType()
   * @generated
   */
  EReference getLayoutType_Entities();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Vertical <em>Vertical</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertical</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Vertical
   * @generated
   */
  EClass getVertical();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Horizontal <em>Horizontal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Horizontal</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Horizontal
   * @generated
   */
  EClass getHorizontal();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Label <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Label
   * @generated
   */
  EClass getLabel();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Button <em>Button</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Button
   * @generated
   */
  EClass getButton();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Input <em>Input</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Input
   * @generated
   */
  EClass getInput();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Checkbox <em>Checkbox</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checkbox</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Checkbox
   * @generated
   */
  EClass getCheckbox();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Specifications <em>Specifications</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Specifications</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Specifications
   * @generated
   */
  EClass getSpecifications();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.guilang.guilang.Specifications#getSpecifications <em>Specifications</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Specifications</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Specifications#getSpecifications()
   * @see #getSpecifications()
   * @generated
   */
  EReference getSpecifications_Specifications();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Specification <em>Specification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Specification</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Specification
   * @generated
   */
  EClass getSpecification();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.Specification#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Specification#getType()
   * @see #getSpecification()
   * @generated
   */
  EReference getSpecification_Type();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.LayoutSpec <em>Layout Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layout Spec</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.LayoutSpec
   * @generated
   */
  EClass getLayoutSpec();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.guilang.guilang.LayoutSpec#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.LayoutSpec#getRef()
   * @see #getLayoutSpec()
   * @generated
   */
  EReference getLayoutSpec_Ref();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.VerticalSpec <em>Vertical Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vertical Spec</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.VerticalSpec
   * @generated
   */
  EClass getVerticalSpec();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.guilang.guilang.VerticalSpec#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.VerticalSpec#getRef()
   * @see #getVerticalSpec()
   * @generated
   */
  EReference getVerticalSpec_Ref();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.HorizontalSpec <em>Horizontal Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Horizontal Spec</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.HorizontalSpec
   * @generated
   */
  EClass getHorizontalSpec();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.guilang.guilang.HorizontalSpec#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.HorizontalSpec#getRef()
   * @see #getHorizontalSpec()
   * @generated
   */
  EReference getHorizontalSpec_Ref();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.LabelSpec <em>Label Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label Spec</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.LabelSpec
   * @generated
   */
  EClass getLabelSpec();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.guilang.guilang.LabelSpec#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.LabelSpec#getRef()
   * @see #getLabelSpec()
   * @generated
   */
  EReference getLabelSpec_Ref();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.ButtonSpec <em>Button Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button Spec</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.ButtonSpec
   * @generated
   */
  EClass getButtonSpec();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.guilang.guilang.ButtonSpec#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.ButtonSpec#getRef()
   * @see #getButtonSpec()
   * @generated
   */
  EReference getButtonSpec_Ref();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.guilang.guilang.ButtonSpec#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Options</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.ButtonSpec#getOptions()
   * @see #getButtonSpec()
   * @generated
   */
  EReference getButtonSpec_Options();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.ButtonSpecOptions <em>Button Spec Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Button Spec Options</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.ButtonSpecOptions
   * @generated
   */
  EClass getButtonSpecOptions();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.InputSpec <em>Input Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Spec</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.InputSpec
   * @generated
   */
  EClass getInputSpec();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.guilang.guilang.InputSpec#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.InputSpec#getRef()
   * @see #getInputSpec()
   * @generated
   */
  EReference getInputSpec_Ref();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.guilang.guilang.InputSpec#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Options</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.InputSpec#getOptions()
   * @see #getInputSpec()
   * @generated
   */
  EReference getInputSpec_Options();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.InputSpecOptions <em>Input Spec Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Spec Options</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.InputSpecOptions
   * @generated
   */
  EClass getInputSpecOptions();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.CheckboxSpec <em>Checkbox Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checkbox Spec</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.CheckboxSpec
   * @generated
   */
  EClass getCheckboxSpec();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.guilang.guilang.CheckboxSpec#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.CheckboxSpec#getRef()
   * @see #getCheckboxSpec()
   * @generated
   */
  EReference getCheckboxSpec_Ref();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.SizeSpec <em>Size Spec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Size Spec</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.SizeSpec
   * @generated
   */
  EClass getSizeSpec();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.guilang.guilang.SizeSpec#getWidth <em>Width</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Width</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.SizeSpec#getWidth()
   * @see #getSizeSpec()
   * @generated
   */
  EAttribute getSizeSpec_Width();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.guilang.guilang.SizeSpec#getHeight <em>Height</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Height</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.SizeSpec#getHeight()
   * @see #getSizeSpec()
   * @generated
   */
  EAttribute getSizeSpec_Height();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Validate <em>Validate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Validate</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Validate
   * @generated
   */
  EClass getValidate();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mdsd.guilang.guilang.Validate#getValidations <em>Validations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Validations</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Validate#getValidations()
   * @see #getValidate()
   * @generated
   */
  EReference getValidate_Validations();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.TextValidate <em>Text Validate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Validate</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.TextValidate
   * @generated
   */
  EClass getTextValidate();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.TextValidate#getValidation <em>Validation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Validation</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.TextValidate#getValidation()
   * @see #getTextValidate()
   * @generated
   */
  EReference getTextValidate_Validation();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.RegexValidate <em>Regex Validate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Regex Validate</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.RegexValidate
   * @generated
   */
  EClass getRegexValidate();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.guilang.guilang.RegexValidate#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.RegexValidate#getValue()
   * @see #getRegexValidate()
   * @generated
   */
  EAttribute getRegexValidate_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.RegexVariableValidate <em>Regex Variable Validate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Regex Variable Validate</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.RegexVariableValidate
   * @generated
   */
  EClass getRegexVariableValidate();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.guilang.guilang.RegexVariableValidate#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.RegexVariableValidate#getValue()
   * @see #getRegexVariableValidate()
   * @generated
   */
  EAttribute getRegexVariableValidate_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.RegexVariableRef <em>Regex Variable Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Regex Variable Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.RegexVariableRef
   * @generated
   */
  EClass getRegexVariableRef();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.guilang.guilang.RegexVariableRef#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.RegexVariableRef#getRef()
   * @see #getRegexVariableRef()
   * @generated
   */
  EReference getRegexVariableRef_Ref();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.PresetTextValidate <em>Preset Text Validate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Preset Text Validate</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.PresetTextValidate
   * @generated
   */
  EClass getPresetTextValidate();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.guilang.guilang.PresetTextValidate#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.PresetTextValidate#getValue()
   * @see #getPresetTextValidate()
   * @generated
   */
  EAttribute getPresetTextValidate_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.CheckboxValidate <em>Checkbox Validate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Checkbox Validate</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.CheckboxValidate
   * @generated
   */
  EClass getCheckboxValidate();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mdsd.guilang.guilang.CheckboxValidate#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.CheckboxValidate#getValue()
   * @see #getCheckboxValidate()
   * @generated
   */
  EAttribute getCheckboxValidate_Value();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.RequireElements <em>Require Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Require Elements</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.RequireElements
   * @generated
   */
  EClass getRequireElements();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.RequireElements#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elements</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.RequireElements#getElements()
   * @see #getRequireElements()
   * @generated
   */
  EReference getRequireElements_Elements();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Require <em>Require</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Require</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Require
   * @generated
   */
  EClass getRequire();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.Require#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Require#getExp()
   * @see #getRequire()
   * @generated
   */
  EReference getRequire_Exp();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Or <em>Or</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Or
   * @generated
   */
  EClass getOr();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.Or#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Or#getLeft()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.Or#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Or#getRight()
   * @see #getOr()
   * @generated
   */
  EReference getOr_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.And <em>And</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.And
   * @generated
   */
  EClass getAnd();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.And#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.And#getLeft()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Left();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mdsd.guilang.guilang.And#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.And#getRight()
   * @see #getAnd()
   * @generated
   */
  EReference getAnd_Right();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.Not <em>Not</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.Not
   * @generated
   */
  EClass getNot();

  /**
   * Returns the meta object for class '{@link dk.sdu.mdsd.guilang.guilang.ElementRef <em>Element Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.ElementRef
   * @generated
   */
  EClass getElementRef();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mdsd.guilang.guilang.ElementRef#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see dk.sdu.mdsd.guilang.guilang.ElementRef#getRef()
   * @see #getElementRef()
   * @generated
   */
  EReference getElementRef_Ref();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GuilangFactory getGuilangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.GUIImpl <em>GUI</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.GUIImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getGUI()
     * @generated
     */
    EClass GUI = eINSTANCE.getGUI();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GUI__MAIN = eINSTANCE.getGUI_Main();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.UnitImpl <em>Unit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.UnitImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getUnit()
     * @generated
     */
    EClass UNIT = eINSTANCE.getUnit();

    /**
     * The meta object literal for the '<em><b>Layout</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNIT__LAYOUT = eINSTANCE.getUnit_Layout();

    /**
     * The meta object literal for the '<em><b>Specifications</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNIT__SPECIFICATIONS = eINSTANCE.getUnit_Specifications();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.EntityImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getEntity_Name();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.LayoutImpl <em>Layout</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.LayoutImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getLayout()
     * @generated
     */
    EClass LAYOUT = eINSTANCE.getLayout();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.LayoutTypeImpl <em>Layout Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.LayoutTypeImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getLayoutType()
     * @generated
     */
    EClass LAYOUT_TYPE = eINSTANCE.getLayoutType();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_TYPE__ENTITIES = eINSTANCE.getLayoutType_Entities();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.VerticalImpl <em>Vertical</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.VerticalImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getVertical()
     * @generated
     */
    EClass VERTICAL = eINSTANCE.getVertical();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.HorizontalImpl <em>Horizontal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.HorizontalImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getHorizontal()
     * @generated
     */
    EClass HORIZONTAL = eINSTANCE.getHorizontal();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.ElementImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.LabelImpl <em>Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.LabelImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getLabel()
     * @generated
     */
    EClass LABEL = eINSTANCE.getLabel();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ButtonImpl <em>Button</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.ButtonImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getButton()
     * @generated
     */
    EClass BUTTON = eINSTANCE.getButton();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.InputImpl <em>Input</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.InputImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getInput()
     * @generated
     */
    EClass INPUT = eINSTANCE.getInput();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.CheckboxImpl <em>Checkbox</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.CheckboxImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getCheckbox()
     * @generated
     */
    EClass CHECKBOX = eINSTANCE.getCheckbox();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.SpecificationsImpl <em>Specifications</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.SpecificationsImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getSpecifications()
     * @generated
     */
    EClass SPECIFICATIONS = eINSTANCE.getSpecifications();

    /**
     * The meta object literal for the '<em><b>Specifications</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPECIFICATIONS__SPECIFICATIONS = eINSTANCE.getSpecifications_Specifications();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.SpecificationImpl <em>Specification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.SpecificationImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getSpecification()
     * @generated
     */
    EClass SPECIFICATION = eINSTANCE.getSpecification();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SPECIFICATION__TYPE = eINSTANCE.getSpecification_Type();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.LayoutSpecImpl <em>Layout Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.LayoutSpecImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getLayoutSpec()
     * @generated
     */
    EClass LAYOUT_SPEC = eINSTANCE.getLayoutSpec();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYOUT_SPEC__REF = eINSTANCE.getLayoutSpec_Ref();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.VerticalSpecImpl <em>Vertical Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.VerticalSpecImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getVerticalSpec()
     * @generated
     */
    EClass VERTICAL_SPEC = eINSTANCE.getVerticalSpec();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VERTICAL_SPEC__REF = eINSTANCE.getVerticalSpec_Ref();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.HorizontalSpecImpl <em>Horizontal Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.HorizontalSpecImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getHorizontalSpec()
     * @generated
     */
    EClass HORIZONTAL_SPEC = eINSTANCE.getHorizontalSpec();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HORIZONTAL_SPEC__REF = eINSTANCE.getHorizontalSpec_Ref();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.LabelSpecImpl <em>Label Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.LabelSpecImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getLabelSpec()
     * @generated
     */
    EClass LABEL_SPEC = eINSTANCE.getLabelSpec();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL_SPEC__REF = eINSTANCE.getLabelSpec_Ref();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ButtonSpecImpl <em>Button Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.ButtonSpecImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getButtonSpec()
     * @generated
     */
    EClass BUTTON_SPEC = eINSTANCE.getButtonSpec();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON_SPEC__REF = eINSTANCE.getButtonSpec_Ref();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUTTON_SPEC__OPTIONS = eINSTANCE.getButtonSpec_Options();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ButtonSpecOptionsImpl <em>Button Spec Options</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.ButtonSpecOptionsImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getButtonSpecOptions()
     * @generated
     */
    EClass BUTTON_SPEC_OPTIONS = eINSTANCE.getButtonSpecOptions();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.InputSpecImpl <em>Input Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.InputSpecImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getInputSpec()
     * @generated
     */
    EClass INPUT_SPEC = eINSTANCE.getInputSpec();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT_SPEC__REF = eINSTANCE.getInputSpec_Ref();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT_SPEC__OPTIONS = eINSTANCE.getInputSpec_Options();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.InputSpecOptionsImpl <em>Input Spec Options</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.InputSpecOptionsImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getInputSpecOptions()
     * @generated
     */
    EClass INPUT_SPEC_OPTIONS = eINSTANCE.getInputSpecOptions();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.CheckboxSpecImpl <em>Checkbox Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.CheckboxSpecImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getCheckboxSpec()
     * @generated
     */
    EClass CHECKBOX_SPEC = eINSTANCE.getCheckboxSpec();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECKBOX_SPEC__REF = eINSTANCE.getCheckboxSpec_Ref();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.SizeSpecImpl <em>Size Spec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.SizeSpecImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getSizeSpec()
     * @generated
     */
    EClass SIZE_SPEC = eINSTANCE.getSizeSpec();

    /**
     * The meta object literal for the '<em><b>Width</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE_SPEC__WIDTH = eINSTANCE.getSizeSpec_Width();

    /**
     * The meta object literal for the '<em><b>Height</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIZE_SPEC__HEIGHT = eINSTANCE.getSizeSpec_Height();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ValidateImpl <em>Validate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.ValidateImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getValidate()
     * @generated
     */
    EClass VALIDATE = eINSTANCE.getValidate();

    /**
     * The meta object literal for the '<em><b>Validations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALIDATE__VALIDATIONS = eINSTANCE.getValidate_Validations();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.TextValidateImpl <em>Text Validate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.TextValidateImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getTextValidate()
     * @generated
     */
    EClass TEXT_VALIDATE = eINSTANCE.getTextValidate();

    /**
     * The meta object literal for the '<em><b>Validation</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEXT_VALIDATE__VALIDATION = eINSTANCE.getTextValidate_Validation();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.RegexValidateImpl <em>Regex Validate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.RegexValidateImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getRegexValidate()
     * @generated
     */
    EClass REGEX_VALIDATE = eINSTANCE.getRegexValidate();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGEX_VALIDATE__VALUE = eINSTANCE.getRegexValidate_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.RegexVariableValidateImpl <em>Regex Variable Validate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.RegexVariableValidateImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getRegexVariableValidate()
     * @generated
     */
    EClass REGEX_VARIABLE_VALIDATE = eINSTANCE.getRegexVariableValidate();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REGEX_VARIABLE_VALIDATE__VALUE = eINSTANCE.getRegexVariableValidate_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.RegexVariableRefImpl <em>Regex Variable Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.RegexVariableRefImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getRegexVariableRef()
     * @generated
     */
    EClass REGEX_VARIABLE_REF = eINSTANCE.getRegexVariableRef();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REGEX_VARIABLE_REF__REF = eINSTANCE.getRegexVariableRef_Ref();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.PresetTextValidateImpl <em>Preset Text Validate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.PresetTextValidateImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getPresetTextValidate()
     * @generated
     */
    EClass PRESET_TEXT_VALIDATE = eINSTANCE.getPresetTextValidate();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRESET_TEXT_VALIDATE__VALUE = eINSTANCE.getPresetTextValidate_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.CheckboxValidateImpl <em>Checkbox Validate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.CheckboxValidateImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getCheckboxValidate()
     * @generated
     */
    EClass CHECKBOX_VALIDATE = eINSTANCE.getCheckboxValidate();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHECKBOX_VALIDATE__VALUE = eINSTANCE.getCheckboxValidate_Value();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.RequireElementsImpl <em>Require Elements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.RequireElementsImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getRequireElements()
     * @generated
     */
    EClass REQUIRE_ELEMENTS = eINSTANCE.getRequireElements();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIRE_ELEMENTS__ELEMENTS = eINSTANCE.getRequireElements_Elements();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.RequireImpl <em>Require</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.RequireImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getRequire()
     * @generated
     */
    EClass REQUIRE = eINSTANCE.getRequire();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REQUIRE__EXP = eINSTANCE.getRequire_Exp();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.OrImpl <em>Or</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.OrImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getOr()
     * @generated
     */
    EClass OR = eINSTANCE.getOr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__LEFT = eINSTANCE.getOr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR__RIGHT = eINSTANCE.getOr_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.AndImpl <em>And</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.AndImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getAnd()
     * @generated
     */
    EClass AND = eINSTANCE.getAnd();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__LEFT = eINSTANCE.getAnd_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND__RIGHT = eINSTANCE.getAnd_Right();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.NotImpl <em>Not</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.NotImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getNot()
     * @generated
     */
    EClass NOT = eINSTANCE.getNot();

    /**
     * The meta object literal for the '{@link dk.sdu.mdsd.guilang.guilang.impl.ElementRefImpl <em>Element Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mdsd.guilang.guilang.impl.ElementRefImpl
     * @see dk.sdu.mdsd.guilang.guilang.impl.GuilangPackageImpl#getElementRef()
     * @generated
     */
    EClass ELEMENT_REF = eINSTANCE.getElementRef();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ELEMENT_REF__REF = eINSTANCE.getElementRef_Ref();

  }

} //GuilangPackage
