/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.guilang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Spec Options</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getInputSpecOptions()
 * @model
 * @generated
 */
public interface InputSpecOptions extends EObject
{
} // InputSpecOptions
