/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.guilang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Regex Validate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.guilang.guilang.RegexValidate#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getRegexValidate()
 * @model
 * @generated
 */
public interface RegexValidate extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getRegexValidate_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.guilang.guilang.RegexValidate#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // RegexValidate
