/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.guilang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.guilang.guilang.Unit#getLayout <em>Layout</em>}</li>
 *   <li>{@link dk.sdu.mdsd.guilang.guilang.Unit#getSpecifications <em>Specifications</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getUnit()
 * @model
 * @generated
 */
public interface Unit extends EObject
{
  /**
   * Returns the value of the '<em><b>Layout</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Layout</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Layout</em>' containment reference.
   * @see #setLayout(Layout)
   * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getUnit_Layout()
   * @model containment="true"
   * @generated
   */
  Layout getLayout();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.guilang.guilang.Unit#getLayout <em>Layout</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Layout</em>' containment reference.
   * @see #getLayout()
   * @generated
   */
  void setLayout(Layout value);

  /**
   * Returns the value of the '<em><b>Specifications</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Specifications</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Specifications</em>' containment reference.
   * @see #setSpecifications(Specifications)
   * @see dk.sdu.mdsd.guilang.guilang.GuilangPackage#getUnit_Specifications()
   * @model containment="true"
   * @generated
   */
  Specifications getSpecifications();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.guilang.guilang.Unit#getSpecifications <em>Specifications</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Specifications</em>' containment reference.
   * @see #getSpecifications()
   * @generated
   */
  void setSpecifications(Specifications value);

} // Unit
