/**
 * generated by Xtext 2.16.0
 */
package dk.sdu.mdsd.guilang.ide;

import dk.sdu.mdsd.guilang.ide.AbstractGuilangIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GuilangIdeModule extends AbstractGuilangIdeModule {
}
